### ISSUE TITLE
Dies on upscale

### ISSUE THREAD

**Issue by benplum** [Fastspot/bigtree-video-field-type#1]
https://github.com/Fastspot/bigtree-video-field-type/blob/master/field-types/video/process.php#L137

**Comment by timbuckingham** [comment]
I'm a dumbo, had this change sitting uncommited in my local repo and never pushed it. Sorry about that!
https://github.com/Fastspot/bigtree-video-field-type/commit/aaaf75ffd43d2887b82b45ca3f08c265d9e8bdc3

I pushed a new release to the extensions archive so it should show up as an update.
